### PR TITLE
Feature/tooltip

### PR DESCRIPTION
**Pull request by JohnTheo13**
Static Tooltips
- Next step Overlay component for both tooltips and popovers
- I used withknobs for better experience (let me know if you like it, so I can add it to popovers)
@xDae

### CODE REVIEW

**Comment by xDae** [comment]
Cool! Thanks @JohnTheo13, im abroad but i will review on monday 👍🏻

**Comment by JohnTheo13** [comment]
@xDae is this project still on, I'm trying to reach you but can't find you, please respond

**Comment by xDae** [comment]
@JohnTheo13 yes! sorry, I have been quite busy because job change

**Comment by JohnTheo13** [comment]
@xDae I totally understand, I just wont to clarify how I should proceed.

**Pull request closed without merging**
